### ISSUE TITLE
Support subdatasets

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#18]
Only installed ones - no need to install. But I guess we need to (re) introduce ability to deduce dataset for unseen yet paths (ie cache association between directories and datasets they belong to)

**Comment by jwodder** [comment]
@yarikoptic So, given a path in a dataset, how do I determine what (sub)dataset it belongs to in the first place?  Do I have to look through the results of `datalad.api.subdatasets()` for the closest parent path?  Can I start at the path's directory, check for datasetness, and work my way up?  Is there another, better way?

**Comment by yarikoptic** [comment]
good question.  Through datalad's history we had a number of implementations  and I think we are brewing even more ;-)  I think since we do not need to establish "parental" relationship (what is the superdataset of a subdataset), I think `datalad.utils.get_dataset_root` on a directory containing that path would suffice.

But since here we are making an assumption of immutability of underlying datasets during FUSE operations, and will query one path at a time, we might either add a cache  (could even just be some built-in `@lru_cache()` on top of that function) .
