### ISSUE TITLE
Initial implementation for fsspec "annex adapter" to provide a sample `datalad fsspec-head` command

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#2]
Currently https://github.com/datalad/datalad-fuse/blob/master/datalad_fuse/fuse_.py provides a prototype of a FUSE filesystem which relies on the [fsspec](https://filesystem-spec.readthedocs.io/en/latest/index.html) to provide access to remote files for which we know a URL. As outlined in https://github.com/datalad/datalad/issues/4003#issuecomment-789779448 it would be better to separate out "fsspec driver" from FUSE, which was somewhat already done in that prototype https://github.com/datalad/datalad-fuse/blob/master/datalad_fuse/fuse_.py#L88 but that fsspecFile is already tuned too much to serve FUSE.

The goal now would be to either create a proper adapter, independent of any FUSE needs, which given an annex repository,

- [ ] interface fsspec as to provide `open` call (probably close in spirit to _get_file https://github.com/datalad/datalad-fuse/blob/master/datalad_fuse/fuse_.py#L141)
  - for that it would need to get URLs associated with the file (note: for now it is ok to just get ones for `web` remote, but later we would extend not only to URLs but other transport mechanisms, such as files available from known ssh remotes etc)
  - use fsspec cache (placed in that repo, under eg. `.git/datalad/cache/fsspec ` - later might need an option to make it global or just point to specific location to be shared) to open it and return that object to the user
  - note: does not need to be done here I guess but - figure out best way to "hook" into `datalad clean` command so it would also remove this cache. need to be looked at
- [ ] to test drive that functionality, create `datalad fsspec-head` (or some other more generic command? `fsspec-dd` or smth like that to be able to do arbitrary offset'ed block?)

**Comment by jwodder** [comment]
@yarikoptic 

> interface fsspec as to provide `open` call

Are you referring to the [`DataLadFUSE.open()`](https://github.com/datalad/datalad-fuse/blob/eb69598c66d5664841f9b61c04fa2bad1d7cdc77/datalad_fuse/fuse_.py#L225) method, or do you want this `open()` call to be located somewhere else?  What should its signature be?

**Comment by yarikoptic** [comment]
Yes I think that method in principle, but without any FUSE related ABI etc, so be moved outside of DataLadFUSE

**Comment by jwodder** [comment]
@yarikoptic Could you elaborate on the API you want implemented?

**Comment by yarikoptic** [comment]
to have the `FsspecAdapter` with
- constructor to take `path` to annex repo
- `open` mimicing builtin `open` but may be just limiting to `file, mode='r'`. relative path relative to the top of the repo
- `clean` - clean up/remove cache

To have `FsspectHead` datalad interface (exposed as command `fsspec-head` in cli, `fsspect_head` within `datalad.api`) with simplistic list of parameters
- `path`
- `-n|--lines` (`lines: int=10`)
- `dataset=None`

**Comment by jwodder** [comment]
@yarikoptic A `--lines` option isn't a good idea for binary files, and for text files (when they're annexed to begin with) knowing the encoding is necessary in order to implement it.  Did you want a `-c`/`--bytes` option instead?

**Comment by yarikoptic** [comment]
sure thing if it is a binary file, use of `--lines` would be inappropriate, but that is what regular `head` is doing if I specify `-n` or leave it without specification.  So I think it is simply for user to judge.
But you are bringing a good point, may be make it `lines: int=0, bytes: int=0` and add logic that if both are not specified (0s) - use `lines=10`. If both specified -- error out (although regular `head` just takes the last option specified between the two -- not something we can/should do in python ;)).
I have never used `--bytes` I think (usually would just use `dd`) with `head`, but now I might ;)

**Comment by jwodder** [comment]
@yarikoptic Should the command return the head data by yielding one or more "status dicts" (in which case, how should they be structured?) or should it just output the data directly to stdout (in which case, should setting both `lines` and `bytes` be handled by simply raising a `ValueError`)?

**Comment by yarikoptic** [comment]
Let's aim for "proper datalad way" indeed - so return a structure. Record -- use `get_status_dict` and e.g. take https://github.com/datalad/datalad/blob/HEAD/datalad/local/wtf.py as an example (custom renderer would then output it to the screen in CLI). It is actually desired to raise `ValueError` (not to return some status dict) in case of misspecification.

**Comment by jwodder** [comment]
@yarikoptic If I return the data in an `info` key as `wtf` does, the data is not displayed when running `datalad fsspec-head` with the default formatter.  As far as I can tell, the only way to display it is by returning it in the `message` key, in which case the output looks like:

```
fsspec-head(ok): /Users/jwodder/dartmouth/dandisets/000003 (dataset) [b'\x89HDF\r\n\x1a\n']
```

**Comment by yarikoptic** [comment]
but we don't want default , we want custom formatter like wtf does. After you add it (since not there yet seems to me - https://github.com/datalad/datalad-fuse/pull/3/files#diff-54e1f480d45904f3d075f68a58d49c33caaf039226005e5f1029c8996762eacfR73) , default one will not be used.

**Comment by jwodder** [comment]
@yarikoptic How can/should a custom formatter print out binary data?  Looking at [`datalad.ui.dialog`](https://github.com/datalad/datalad/blob/master/datalad/ui/dialog.py), it seems that it only supports outputting `str` objects.

**Comment by yarikoptic** [comment]
I guess may be just use `sys.stdout.write` for now (to result in output identical to a regular `head` output?) and then we will see if we should improve `ui` to allow for binary dumps
