### ISSUE TITLE
there seems to be no persistent (reused in subsequent runs) fsspec cache

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#27]
full log from running

```shell
DATALAD_LOG_TIMESTAMP=1 DATALAD_LOG_NAME=1 datalad -l debug fusefs -f -d ~/datalad /mnt/datalad 2>&1 | tee /tmp/fuse.log
```

is here http://www.onerussian.com/tmp/fuse-20211203.log .

After initiating that process, I did

```
lena:~
$> cd -1 
/mnt/datalad/openneuro
ds000001/  ....
lena:/mnt/datalad/openneuro
$> time nib-ls ds000001/sub*/anat/*nii.gz                                                         
ds000001/sub-01/anat/sub-01_inplaneT2.nii.gz int16 [128, 128,  33] 1.56x1.56x4.00
ds000001/sub-01/anat/sub-01_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-02/anat/sub-02_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-02/anat/sub-02_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-03/anat/sub-03_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-03/anat/sub-03_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-04/anat/sub-04_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-04/anat/sub-04_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-05/anat/sub-05_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-05/anat/sub-05_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-06/anat/sub-06_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-06/anat/sub-06_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33   sform
ds000001/sub-07/anat/sub-07_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-07/anat/sub-07_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-08/anat/sub-08_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-08/anat/sub-08_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-09/anat/sub-09_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-09/anat/sub-09_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-10/anat/sub-10_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-10/anat/sub-10_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-11/anat/sub-11_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-11/anat/sub-11_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-12/anat/sub-12_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-12/anat/sub-12_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-13/anat/sub-13_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-13/anat/sub-13_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-14/anat/sub-14_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-14/anat/sub-14_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-15/anat/sub-15_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-15/anat/sub-15_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-16/anat/sub-16_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-16/anat/sub-16_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33

nib-ls ds000001/sub*/anat/*nii.gz  0.30s user 0.26s system 2% cpu 19.101 total
1 27571.....................................:Fri 03 Dec 2021 03:05:58 PM EST:.
lena:/mnt/datalad/openneuro
$> time nib-ls ds000001/sub*/anat/*nii.gz
ds000001/sub-01/anat/sub-01_inplaneT2.nii.gz int16 [128, 128,  33] 1.56x1.56x4.00
ds000001/sub-01/anat/sub-01_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-02/anat/sub-02_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-02/anat/sub-02_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-03/anat/sub-03_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-03/anat/sub-03_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-04/anat/sub-04_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-04/anat/sub-04_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-05/anat/sub-05_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-05/anat/sub-05_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-06/anat/sub-06_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-06/anat/sub-06_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33   sform
ds000001/sub-07/anat/sub-07_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-07/anat/sub-07_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-08/anat/sub-08_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-08/anat/sub-08_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-09/anat/sub-09_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-09/anat/sub-09_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-10/anat/sub-10_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00
ds000001/sub-10/anat/sub-10_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-11/anat/sub-11_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-11/anat/sub-11_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-12/anat/sub-12_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-12/anat/sub-12_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-13/anat/sub-13_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-13/anat/sub-13_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-14/anat/sub-14_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-14/anat/sub-14_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-15/anat/sub-15_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-15/anat/sub-15_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33
ds000001/sub-16/anat/sub-16_inplaneT2.nii.gz int16 [128, 128,  34] 1.56x1.56x4.00   sform
ds000001/sub-16/anat/sub-16_T1w.nii.gz       int16 [160, 192, 192] 1.00x1.33x1.33

nib-ls ds000001/sub*/anat/*nii.gz  0.30s user 0.24s system 2% cpu 19.472 total

```

so both nib-ls invocations took the same 19 sec, and I saw identical patterns of internet traffic.  And I found no persistent fsspec cache in the openneuro super (shouldn't be there, just wanted to check), nor in ds000001:

```
(git-annex)lena:~/datalad/openneuro[master]git-annex
$> ls -l {,ds000001/}.git/datalad/cache/      
ls: cannot access '.git/datalad/cache/': No such file or directory
ls: cannot access 'ds000001/.git/datalad/cache/': No such file or directory
```

I expected that initial invocation of `nib-ls` (from nibabel package) would initiate sparse cached local version of all those files, so the 2nd invocation should go fast and not download anything from online.

FWIW fsspec version 2021.10.1

**Comment by jwodder** [comment]
@yarikoptic As the dataset path supplied to the fusefs command was `~/datalad`, the cache should be located at `~/datalad/.git/datalad/cache/fsspec`; is there a cache there?

**Comment by jwodder** [comment]
@yarikoptic When I tried running the `nib-ls` command, starting out with a clean cache, the first run took 23 seconds, and the second took 18 seconds.

**Comment by yarikoptic** [comment]
> ~/datalad/.git/datalad/cache/fsspec

oh, yes (has quite a bit)... I should have checked that location too - my bad. Cleaned that one, redid nib-ls . Initial run was 48 sec, cache became 87M in size (total non-sparse is 92M, so seems fetching nearly full files... will look into it separately), reran -- also 48 sec, saw similar network traffic displayed on gkrellm sidebar.  So there is more to it I guess :-/  difference between 23 and 18 sec for you is suggestive that it was fetching again -- when files are present locally, that `nib-ls` call is taking 0.4 sec for me. 

But also, overall, cache should be dataset specific.  Rationale:
- On one run we might mount topmost superdataset, on another specific subdataset.  Shared common cache would then make them all "separate"
- If we uninstall subdataset, there is no reason to keep its cache.  If cache is shared -- we would not even be able to clean it up for uninstalled subdatasets
- Shared cache could grow too large.

**Comment by jwodder** [comment]
@yarikoptic Should the `fsspec-cache-clear` command then clean up only the cache for the root dataset or all subdatasets as well?

**Comment by yarikoptic** [comment]
please add `-r|--recursive` option which would explicitly instruct to go through all (installed AKA fulfilled) subdatasets and clean in them as well.

**Comment by jwodder** [comment]
@yarikoptic When operating recursively, I assume that the command should yield status dicts for each subdataset as well, correct?  Should each status dict set `ds` to the subdataset, or should `ds` always be the root dataset with `path` or something else set to the path to the subdataset?

**Comment by yarikoptic** [comment]
> @yarikoptic When operating recursively, I assume that the command should yield status dicts for each subdataset as well, correct?

correct

> Should each status dict set `ds` to the subdataset, or should `ds` always be the root dataset with `path` or something else set to the path to the subdataset?

Use this `get_status_dict` to mint the return record: https://github.com/datalad/datalad/blob/HEAD/datalad/interface/results.py#L51

you can see that it "decomposes" `ds` into `path` + `type="dataset"` (for better or for worse).  Then provide `refds` pointing to the "original" (super)dataset for which command was invoked.  There could also be `parentds` if you know what it is (if not -- that is ok).

**Comment by yarikoptic** [comment]
Thanks for the #28, merged that one . Now it is left to figure out why that cache is not really "persistent", i.e. seems to be not really in effect for the next invocation, as I described [above](https://github.com/datalad/datalad-fuse/issues/27#issuecomment-987279440)

**Comment by jwodder** [comment]
@yarikoptic I just tried out `fsspec-cache-clear` with the new `-r` option in a clone of datasets.datalad.org where most of the subdatasets weren't installed and got this:

```
fsspec-cache-clear(ok): /home/vagrant/fuse-test/datasets.datalad.org (dataset)
subdataset(ok): abide (dataset)
subdataset(ok): abide2 (dataset)
subdataset(ok): adhd200 (dataset)
[snipped: "ok" for every other subdataset]
subdataset(ok): workshops (dataset)
[ERROR  ] PathKnownToRepositoryError(Failing to initialize new repository under /home/vagrant/fuse-test/datasets.datalad.org/abide where following files are known to a repository above: ./) (PathKnownToRepositoryError)
```

I don't understand the error.  Why is datalad trying to initialize a new repository in "abide"?

**Comment by jwodder** [comment]
@yarikoptic The lack of persistent caching seems to be due a bug in fsspec; [I've filed an issue](https://github.com/fsspec/filesystem_spec/issues/845).

**Comment by yarikoptic** [comment]
> [ERROR  ] PathKnownToRepositoryError(Failing to initialize new repository under /home/vagrant/fuse-test/datasets.datalad.org/abide where following files are known to a repository above: ./) (PathKnownToRepositoryError)

I have pushed a fix in 230248ef02c4a77f659f7d3577d13c367c5fb82a for this issue.  Also pushed 670138c7871d73b889a31264654b032ee964074c tune up to avoid rendering of those subdatasets records (really not sure why we do that ;))

**Comment by yarikoptic** [comment]
fsspec issue was fixed ! hooray. @jwodder please verify/confirm here that we are gaining expected behavior with that fix.

**Comment by jwodder** [comment]
@yarikoptic Yes, running `md5sum ds000001/sub*/anat/*nii.gz` with an empty cache takes 15.5s, while subsequent runs take about half a second.

**Comment by yarikoptic** [comment]
Awesome! Let's consider this issue resolved. I will give it all a test ride soon enough

**Comment by yarikoptic** [comment]
Although I wonder, do you see an easy way to craft a unit test for this situation?

**Comment by jwodder** [comment]
@yarikoptic Not as part of datalad-fuse; I already added a test to fsspec, though.
