### ISSUE TITLE
fusefs: an option (or config) to clean up caches for all "considered" datasets upon exit

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#32]
Orthogonal but related to https://github.com/datalad/datalad-fuse/issues/31 . I think it should just be a config variable (not option), such as `datalad.fusefs.cache-clear` (or alike) with possible choices (besides being left unspecified) : `recursive`, `visited`. If set, upon exit, fusefs should call `fsspec-cache-clear`  within those datasets which were "visited" through fusefs runtime (`visited`) or just recursively from the top (if `recursive`).

**Comment by jwodder** [comment]
@yarikoptic How/where should this config variable be declared?  Or should the code just do `cfg.get("datalad.fusefs.cache-clear")`?

**Comment by yarikoptic** [comment]
similarly to #31 , we would need to wait for https://github.com/datalad/datalad/issues/6314 to be "resolved". Meanwhile indeed just use `cfg.get` (I think, no need for `cfg.obtain`)

**Comment by yarikoptic** [comment]
FTR: solved without "registering" that configuration in common_cfg of datalad-core, but just using/referring to that config in https://github.com/datalad/datalad-fuse/pull/37/files#diff-9ecef4f4bd763d8738d14a47bafe14a54cb42520c194bdc09e41c913506c9061R66
