### ISSUE TITLE
Adjust (well, at large rewrite) README.md to provide a brief description/HOWTO

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#38]
ATM it is still from a template.

**Comment by jwodder** [comment]
@yarikoptic The README currently has a badge for Appveyor CI status pointing to the builds for datalad-extension-template, while this repo does not seem to have Appveyor enabled for it, despite having an `.appveyor.yml` file; should Appveyor be enabled, or should the badge & config be removed?  Similarly, should badges for the `test.yml` and/or `test-libfuse.yml` workflows be added?
