### ISSUE TITLE
Add intuit auto, cut a release (0.1.0), and upload to PyPI

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#39]

**Comment by jwodder** [comment]
@yarikoptic It appears that we need to create a release before setting up auto.  I'll do that once #40 and #41 are merged.

**Comment by jwodder** [comment]
Release created (https://github.com/datalad/datalad-fuse/releases/tag/0.1.0) and uploaded to PyPI (https://pypi.org/project/datalad-fuse/0.1.0/).
