### ISSUE TITLE
du -m (but not -b) in --mode-transparent on .git/ files reports 0

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#47]
most likely some kind of a bug in `du` but it is odd

```
(git-annex)lena:/tmp/mnt[master]
$> du -scb .git/datalad
95974410	.git/datalad
95974410	total

$> du -sck .git/datalad
0	.git/datalad
0	total

$> du -sch .git/datalad
0	.git/datalad
0	total

```
so whenever I ask for units other than bytes, I get 0.  (with `--apparent- size it seems to do the right job)

Any ideas @jwodder - may be I am missing smth or it is a `du` bug (FTR I have coreutils 8.32-4.1)?

edit 1:
<details>
<summary>it is not just about our possibly sparse files</summary> 

```shell
lena:/tmp
$> du -h mnt/.git/       
0	mnt/.git/branches
0	mnt/.git/hooks
0	mnt/.git/info
0	mnt/.git/refs/heads
0	mnt/.git/refs/tags
0	mnt/.git/refs/remotes/origin
0	mnt/.git/refs/remotes
0	mnt/.git/refs/annex
0	mnt/.git/refs
0	mnt/.git/objects/pack
0	mnt/.git/objects/info
0	mnt/.git/objects/a5
0	mnt/.git/objects/f8
0	mnt/.git/objects/f3
0	mnt/.git/objects
0	mnt/.git/logs/refs/remotes/origin
0	mnt/.git/logs/refs/remotes
0	mnt/.git/logs/refs/heads
0	mnt/.git/logs/refs
0	mnt/.git/logs
0	mnt/.git/annex/keysdb
0	mnt/.git/annex/journal
0	mnt/.git/annex
0	mnt/.git/datalad/cache/fsspec
0	mnt/.git/datalad/cache
0	mnt/.git/datalad
0	mnt/.git/
1 35633.....................................:Mon 31 Jan 2022 09:30:10 AM EST:.
lena:/tmp
$> du -h --apparent-size mnt/.git/
0	mnt/.git/branches
24K	mnt/.git/hooks
290	mnt/.git/info
112	mnt/.git/refs/heads
0	mnt/.git/refs/tags
40	mnt/.git/refs/remotes/origin
52	mnt/.git/refs/remotes
61	mnt/.git/refs/annex
267	mnt/.git/refs
389K	mnt/.git/objects/pack
0	mnt/.git/objects/info
374	mnt/.git/objects/a5
3.7K	mnt/.git/objects/f8
239	mnt/.git/objects/f3
393K	mnt/.git/objects
212	mnt/.git/logs/refs/remotes/origin
224	mnt/.git/logs/refs/remotes
569	mnt/.git/logs/refs/heads
817	mnt/.git/logs/refs
1.1K	mnt/.git/logs
65K	mnt/.git/annex/keysdb
0	mnt/.git/annex/journal
109K	mnt/.git/annex
92M	mnt/.git/datalad/cache/fsspec
92M	mnt/.git/datalad/cache
92M	mnt/.git/datalad
93M	mnt/.git/

```
</details>

**Comment by jwodder** [comment]
@yarikoptic I don't know what's going on here.  The only relevant thing I could find with a quick search was [this ten-year old post](https://marc.info/?l=fuse-devel&m=133719974600530&w=2).

**Comment by yarikoptic** [comment]
ha, fun, ... I still felt it is `du` level of a bug since IMHO conversion from `-b` should have nothing with underlying layer, was about to file a bug report (seems to fall under debian BTS from the looks of https://debbugs.gnu.org/cgi/pkgreport.cgi?pkg=coreutils) but then decided to RTFM, `man du` says

```
       -b, --bytes
              equivalent to '--apparent-size --block-size=1'
...
       -m     like --block-size=1M
```
so the point is that `-m` (and likely others) doesn't include `--apparent-size` thus creating such a difference in underlying semantic of `-b` vs others.  Given the age of the tool, I guess "it is what it is" and indeed the issue is more of FUSE layer somehow. Let's just be aware of it I guess
