### ISSUE TITLE
--mode-transparent: provide support for `git status`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#48]
Follow up to #46 which established a new mode of operation providing more "natural" view of git-annex'ed repository under FUSE.  But I think, following an item in that issue, we should pursue it a little further and allow for minimal "read-write" capabilities so that `git-annex` (and `git`) could perform `git status`.

ATM for me it looks like

```
(git-annex)lena:/tmp/mnt[master]
$> git status
sqlite worker thread crashed: user error (SQLite3 returned ErrorIO while attempting to perform prepare "SELECT null from content limit 1": disk I/O error(while opening database connection))
git-annex: sqlite query crashed: thread blocked indefinitely in an MVar operation
CallStack (from HasCallStack):
  error, called at ./Database/Handle.hs:79:40 in main:Database.Handle
error: external filter 'git-annex smudge --clean -- %f' failed 1
error: external filter 'git-annex smudge --clean -- %f' failed
sqlite worker thread crashed: user error (SQLite3 returned ErrorIO while attempting to perform prepare "SELECT null from content limit 1": disk I/O error(while opening database connection))
git-annex: sqlite query crashed: thread blocked indefinitely in an MVar operation
CallStack (from HasCallStack):
  error, called at ./Database/Handle.hs:79:40 in main:Database.Handle
error: external filter 'git-annex smudge --clean -- %f' failed 1
error: external filter 'git-annex smudge --clean -- %f' failed
^C
```

**Comment by jwodder** [comment]
@yarikoptic I've made some progress on the gh-48 branch, but I can't figure out how to proceed any further.  Using this branch, `git status` succeeds if the `[filter "annex"]` block is commented out of the mounted dataset's `.git/config`, though it refreshes the index every time it's run.  If the filter block is not commented out, then the git-annex filters will still produce the error messages you saw, and I can't figure out what operation git-annex is even trying & failing on.

**Comment by yarikoptic** [comment]
Thank you, I will check it out!
BTW -- what git annex version you are using?  may be we should try with `-c annex.merge-annex-branches=false` switch for which support across annex commands was improved recently (https://git-annex.branchable.com/bugs/merge-annex-branches__61__false_-_automate_and_extend/) . For a "trial" I guess could be just set in `.git/config` temporarily to see if of any good effect

**Comment by yarikoptic** [comment]
on above note -- since we are the mighty FUSE -- we could even provide a "tuned" `.git/config` content (not original vanilla .git/config) for ever repo which would have that setting set so git-annex doesn't try to do any read-write operation.

**Comment by jwodder** [comment]
@yarikoptic 

> what git annex version you are using?

git annex 8.20211123+git12-g02e3756bd-1~ndall+1

> may be we should try with `-c annex.merge-annex-branches=false` switch

Setting that option in `~/.gitconfig` doesn't help.

**Comment by yarikoptic** [comment]
well, those major fixups were done in [8.20211123-120-g6d7ecd9e5 AKA 8.20211231~20](https://git.kitenet.net/index.cgi/git-annex.git/commit/?id=6d7ecd9e5d1571d1dc7e59106f848abccdf7fd0e) I believe

**Comment by jwodder** [comment]
@yarikoptic It appears that git-annex is trying & failing to do a lock operation, which is not implemented by default for `fuse.Operations`.  Unfortunately, trying to implement a `lock` as follows (using the definition of `@write_op` from commit ce4adb6):

```python
@write_op
def lock(self, path, fh, cmd, lock):
    return os.lockf(fh, cmd, lock)
```

ends up with the `os.lockf` call raising an "Invalid argument" error.

**Comment by yarikoptic** [comment]
```
In [2]: os.lockf?
Signature: os.lockf(fd, command, length, /)
Docstring:
Apply, test or remove a POSIX lock on an open file descriptor.

fd
  An open file descriptor.
command
  One of F_LOCK, F_TLOCK, F_ULOCK or F_TEST.
length
  The number of bytes to lock, starting at the current position.
Type:      builtin_function_or_method
```
so the 3rd arg is `length` not `lock` -- may be that matters?

**Comment by jwodder** [comment]
@yarikoptic The argument name only matters when passing by keyword, which is not done here.  Defining `lock` with `fcntl.lockf()` doesn't help.
