### ISSUE TITLE
Add support to "open" via fsspec from http* remote urls

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#6]
#3 implemented support for fetching from explicitly associated with a key URLs.

Quite often e.g. https://datasets.datalad.org/labs/churchland/najafi-2018-nwb/.git (browser: https://datasets.datalad.org/?dir=/labs/churchland/najafi-2018-nwb) we provide/host data from our server/that remote.  Or even it might reside on gin git-annex-enabled repo, e.g. https://gin.g-node.org/lnnrtwttkhn/highspeed-bids/ .

We should provide support which would "mint" URLs to pass to fsspec.

- `git annex whereis` provides information from which remotes the file is available. For each one of those remotes:
  - If remote UUID is known to git (identify by `remote.{remote}.annex-uuid`; annex adds its name in output of `annex whereis` within description but I think it is better to avoid parsing the "description") and has `http{,s}` url, it could be considered/tried as a URL to fetch from
  - it is needed to create ("mint") candidate URL to try fetching from:
    - figure out the annex key for the file (`git annex lookupkey` or `AnnexRepo.get_file_key`)
    - ~~use `git-annex examinekey --format='${objectpath}\n'` on that key while running in the top of the repo (datalad/local/addurls.py uses it too but we do not have exposed within AnnexRepo)~~ (insufficient)
    - use `git-annex examinekey` with both `hashdirmixed` (regular git repos), and `hashdirlower` ("bare" repos etc)  to figure out possible paths on the remote. 
    - if there is `/.git` trailer in URL, means that most likely repo is not bare -- so try `hashdirmixed` first and then `hashdirlower`. If there is no `/.git` -- candidates in reverse.
    - mint URL by joining remote's URL (with trailing /) and path to the key provided by git-annex
      - if URL did not have `/.git` -- also try candidates with `/.git` 
    - try that URL

<details>
<summary>an example "walkthrough" a file on gin remote </summary> 

```shell
(git-annex)lena:/tmp/highspeed-bids[master]
$> git annex whereis participants.json
whereis participants.json (5 copies) 
  	2616fba7-81bf-40cd-8812-ab38f3eca8d8 -- wittkuhn@master:/mnt/beegfs/home/wittkuhn/highspeed/highspeed-bids
   	662bcf1d-7e57-43b2-b999-393230420e23 -- wittkuhn@lip-osx-003854:~/Documents/highspeed/highspeed-bids
   	762a1cb9-55a0-4b51-a63f-a0b85316d575 -- gin [origin]
   	a7cd184b-62c3-4d36-bb53-59ddee67636c -- yoh@lena:/tmp/highspeed-bids [here]
   	af0e99c7-c24c-49b1-9c4c-968a0dad9ff7 -- keeper
ok

$> git remote show -n origin          
* remote origin
  Fetch URL: https://gin.g-node.org/lnnrtwttkhn/highspeed-bids/
  Push  URL: https://gin.g-node.org/lnnrtwttkhn/highspeed-bids/
  HEAD branch: (not queried)
  Remote branches: (status not queried)
    git-annex
    master
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push' (status not queried):
    (matching) pushes to (matching)

$> git annex lookupkey participants.json                                                     
MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json
(dev3) 1 16467.....................................:Tue 21 Sep 2021 01:06:17 PM EDT:.
(git-annex)lena:/tmp/highspeed-bids[master]
$> git-annex examinekey --format='.git/annex/objects/${hashdirmixed}${key}/${key}\n' MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json
.git/annex/objects/p0/4v/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json

$> curl https://gin.g-node.org/lnnrtwttkhn/highspeed-bids/.git/annex/objects/p0/4v/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json 2>&1 | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!DOCTYPE html>
<html>
<head data-suburl="">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
	
		<meta name="author" content="G-Node"/>
		<meta name="description" content="GIN is a data repository for science"/>

$> git-annex examinekey --format='.git/annex/objects/${hashdirlower}${key}/${key}\n' MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json
.git/annex/objects/c00/411/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json

$> curl https://gin.g-node.org/lnnrtwttkhn/highspeed-bids/.git/annex/objects/c00/411/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json 2>&1 | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!DOCTYPE html>
<html>
<head data-suburl="">
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
	
		<meta name="author" content="G-Node"/>
		<meta name="description" content="GIN is a data repository for science"/>

$> curl https://gin.g-node.org/lnnrtwttkhn/highspeed-bids/annex/objects/c00/411/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json/MD5E-s1064--8804d3d11f17e33bd912f1f0947afdb9.json 2>&1 | head    
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1064  100  1064    0     0   1044      0  0:00:01  0:00:01 --:--:--  1044
{
    "participant_id": {
        "Description": "Participant identifier"
    },
    "age": {
        "Description": "Age, in years as in the first session",
        "Units": "years"

```
</details>

edit 1: provided more information

edit 2: while developing for it, keep in mind that later we might expand to other remote RIs, e.g. ssh remotes. I just didn't want to add it here since first we would need to check on how to ensure that we do or do not prompt user for passwords etc.

**Comment by jwodder** [comment]
@yarikoptic To be clear, this construction of additional candidate URLs should be done by [`get_urls()`](https://github.com/datalad/datalad-fuse/blob/c51b74dbe0f7dbad358832cf979582d19344affc/datalad_fuse/fsspec.py#L27) after it exhausts the "normal" whereis URLs, correct?

**Comment by yarikoptic** [comment]
yes
