### ISSUE TITLE
add a "test" that terminated 'datalad fusefs' is not lingering around

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#66]
The idea came up in the https://github.com/datalad/datalad-fuse/pull/61/files#r802036774 RFing.  Now that there is a singular convenient location for start/stop of the fusefs in a wide range of tests, and we know that eventual test hanging (#56) was coinciding with prior fusefs processes not terminating properly as they should, I keep thinking that it could be of great value to add that testing I was talking in https://github.com/datalad/datalad-fuse/pull/61/files#r802036774 to guarantee that no changes in git-annex, datalad, coverage, whatnot would cause unexpectedly lingering `datalad fusefs` processes left behind.

**Comment by jwodder** [comment]
@yarikoptic So should `fusing()` just wait a few seconds for the fusefs process to exit after calling `terminate()` and error if it doesn't?

**Comment by yarikoptic** [comment]
yeap, I think so
