### ISSUE TITLE
fsspec 2022.10.0 broke datalad-fuse (tests)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-fuse#79]
first failing run was yesterday on cron https://github.com/datalad/datalad-extensions/actions/runs/3286677625/jobs/5415035117 and prior run was good with fsspec 2022.8.2 . I think all tests within `test_fsspec_head.py` are failing now. Look like

```
self = <fsspec.implementations.cached.CachingFileSystem object at 0x7f10a3ca3250>
f = <File-like object HTTPFileSystem, http://127.0.0.1:35169/text.txt>
close = <bound method AbstractBufferedFile.close of <File-like object HTTPFileSystem, http://127.0.0.1:35169/text.txt>>

    def close_and_update(self, f, close):
        """Called when a file is closing, so store the set of blocks"""
        if f.closed:
            return
        path = self._strip_protocol(f.path)
    
>       c = self.cached_files[-1][path]
E       KeyError: '/text.txt'

/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/fsspec/implementations/cached.py:357: KeyError
```

if it is a bug in fsspec -- should be reported to fsspec but may be it is just some changed behavior

**Comment by jwodder** [comment]
@yarikoptic It's a bug; issue filed: https://github.com/fsspec/filesystem_spec/issues/1078

**Comment by yarikoptic** [comment]
Thank you!!!

**Comment by jwodder** [comment]
@yarikoptic Is there any reason to keep this issue open?

**Comment by yarikoptic** [comment]
I am not aware of any -- https://github.com/fsspec/filesystem_spec/issues/1078 seems to be resolved.  Let's close. And feel welcome to close issues you consider resolved (with a comment on why you consider them resolved if they aren't closed by a PR).
